Integration test
CESARBR/knot-cloud-sdk-c pull request #13
Opened 2020-09-11 16:54 UTC by CaioCordeiro

This patch adds a integration test.
Changes : 
- Adds test folder and the integration test file;
- Adds the producer part to the integration test;
- Adds the consumer part of the integration test.
-  Add the integration test compilation script to the automake
so it can be runned with the 'make check' command;
- Add the test commands to the README.

2020-10-08 15:02 UTC, alla3 commented on test/integration/integration_test.c
> +
Remove the blank line

2020-10-13 15:51 UTC, luigiluz requested changes
Awesome PR! Just made a few remarks, let me know when you take a look at them!

2020-10-13 15:51 UTC, luigiluz commented on test/integration/integration_test.c
> +#include <assert.h>
I believe that this header is being included twice

2020-10-13 15:51 UTC, luigiluz commented on test/integration/integration_test.c
> +static bool on_recived_msg(const struct knot_cloud_msg *msg,
```suggestion
static bool on_received_msg(const struct knot_cloud_msg *msg,
```

2020-10-13 15:51 UTC, luigiluz commented on test/integration/integration_test.c
> +
I don't think these two blank lines are necessary, if they aren't, please remove them.

2020-10-13 15:51 UTC, luigiluz commented on test/integration/integration_test.c
> +	l_queue_destroy(schema_queue,NULL);
```suggestion
	l_queue_destroy(schema_queue, NULL);
```

2020-10-13 15:51 UTC, luigiluz commented on test/integration/integration_test.c
> +	knot_cloud_read_start("5b620bcd419afed7", on_recived_msg, NULL);
You're using this id multiple times in the entire code, maybe it would be nice to create a few defines to avoid using the same value a lot of times. (Maybe it would be nice to have all these constants as defines, please consider this if it won't cause you much trouble)

2020-10-13 16:06 UTC, luigiluz commented
Also in the commit [bdbeb15](https://github.com/CESARBR/knot-cloud-sdk-c/pull/13/commits/bdbeb15149aa14b5209f9774eb4b5f3c81bf4aa7) there's a typo in the commit message body.

Please change "parto" to "part"

2020-10-14 19:24 UTC, CaioCordeiro commented on test/integration/integration_test.c
> +#include <assert.h>
Done

2020-10-14 19:24 UTC, CaioCordeiro commented on test/integration/integration_test.c
> +static bool on_recived_msg(const struct knot_cloud_msg *msg,
Done

2020-10-14 19:24 UTC, CaioCordeiro commented on test/integration/integration_test.c
> +
Done

2020-10-14 19:24 UTC, CaioCordeiro commented on test/integration/integration_test.c
> +	l_queue_destroy(schema_queue,NULL);
Done

2020-10-14 19:24 UTC, CaioCordeiro commented on test/integration/integration_test.c
> +	knot_cloud_read_start("5b620bcd419afed7", on_recived_msg, NULL);
Done

2020-10-16 13:14 UTC, luigiluz approved these changes

2020-11-09 11:41 UTC, agms-cesar commented on tests/scripts/integration_test.sh
> +	CURR_TRY=0
you can name those local variables lower_case

2020-11-09 11:42 UTC, agms-cesar commented on tests/scripts/integration_test.sh
> +	docker run -d --hostname "$DOCKER_HOSTNAME" --name "$DOCKER_NAME" \
you can capture the output of this command and validate if it ran successfully

2023-04-13 18:52 UTC, closed without merging