Fix memory issue with timestamp variable
CESARBR/knot-cloud-sdk-c pull request #18
Opened 2022-06-03 19:37 UTC by rtorresmatheus

Added guardian condition for timestamp variable;

2022-06-23 19:09 UTC, vitbaq requested changes

2022-06-23 19:09 UTC, vitbaq commented on src/parser.c
> +		strftime(buf, 32, "%Y-%m-%dT%X.0%z", ptm);
Put theses braces to keep the coding style
(https://www.kernel.org/doc/html/v4.10/process/coding-style.html#placing-braces-and-spaces)

```suggestion
	} else {
		strftime(buf, 32, "%Y-%m-%dT%X.0%z", ptm);
	}
```

2022-07-05 13:45 UTC, alla3 approved these changes

2022-07-05 14:17 UTC, vitbaq approved these changes

2022-07-05 14:17 UTC, merged