Add the possibility of reading with more dataitens
CESARBR/knot-cloud-sdk-c pull request #19
Opened 2022-09-09 16:16 UTC by rtorresmatheus

Add the possibility of reading with more dataitens:

- Added full-time flow to all tags;
- Modified the type of variable responsible for sensor id.

2022-09-09 17:50 UTC, luisfelipemisi reviewed
Really nice code, immaculate as always, with only a few numbers I don't understand.

2022-09-09 17:50 UTC, luisfelipemisi commented on src/parser.c
> +		if (get_sensor_id(&sensor_id_aux, jobjentry) < 0) {
I think the number zero should be replaced by a variable with an explicit name

2022-09-09 17:50 UTC, luisfelipemisi commented on src/parser.c
>  		if (get_schema(&config->schema, jobjentry) < 0) {
I think the number zero should be replaced by a variable with an explicit name.

2022-09-09 18:26 UTC, AntonioJanael requested changes

2022-09-09 18:26 UTC, AntonioJanael commented on src/parser.c
> +		strftime(buf, 32, "%Y-%m-%dT%X.0%z", ptm);
What does this 32 mean? Would it be worth assigning this value to a constant?

2022-09-09 18:26 UTC, AntonioJanael commented on src/knot_cloud.c
> -int knot_cloud_publish_data(const char *id, uint8_t sensor_id,
Why change from uint8_t to int? What do you think about including a comment explaining the reason for using int?

2022-09-12 20:15 UTC, AntonioJanael approved these changes

2022-09-13 11:42 UTC, merged