Create log configuration functions
CESARBR/knot-cloud-sdk-c pull request #4
Opened 2020-08-12 14:53 UTC by CaioCordeiro

Changes:

- Create src/log.c and src/log.h and Add them to src/Makefile.am;
- Create ell lib configuration functions;
- Include log.h in knot_cloud.c;
- Setup log configurations inside knot_cloud_start function;
- Create knot_cloud_set_log_priority, this function lets the user
choose the SDK log priority level;
- Add function to knot_cloud.h

2020-08-13 11:08 UTC, luigiluz requested changes

2020-08-13 11:08 UTC, luigiluz commented on src/log.c
> + * Copyright (c) 2019, CESAR. All rights reserved.
```suggestion
 * Copyright (c) 2020, CESAR. All rights reserved.
```

2020-08-13 11:08 UTC, luigiluz commented on src/log.c
> +}
Please add a blank line at the end of the file

2020-08-13 11:08 UTC, luigiluz commented on src/log.c
> +
```suggestion

/**
 *  Log source file
 */
 
```

2020-08-13 11:08 UTC, luigiluz commented on src/log.h
> + * Copyright (c) 2019, CESAR. All rights reserved.
```suggestion
 * Copyright (c) 2020, CESAR. All rights reserved.
```

2020-08-13 11:08 UTC, luigiluz commented on src/log.h
> +
```suggestion

/**
 *  Log header file
 */
 
```

2020-08-13 11:08 UTC, luigiluz commented on src/log.h
> +void log_ell_enable();
Please add a blank line at the end of the file

2020-08-13 19:08 UTC, alla3 requested changes

2020-08-13 19:08 UTC, alla3 commented on src/knot_cloud.c
> +    if (!strcmp(priority,"error"))
This indentation is using spaces instead of tab. Please, change it.

2020-08-13 19:08 UTC, alla3 commented on src/knot_cloud.c
> +}
This function is not following the same order of the header.

2020-08-13 19:08 UTC, alla3 commented on src/log.c
> +}
I would add this function on commit 9944be4700a2e2088b1afc89e85da0204767ffd1, since it is not been used on this commit.

2020-08-17 16:42 UTC, vitbaq requested changes

2020-08-17 16:42 UTC, vitbaq commented on src/log.c
> +void log_set_priority(int priority)
Put a space before this line

2020-08-17 17:19 UTC, alla3 requested changes

2020-08-17 17:19 UTC, alla3 commented on src/knot_cloud.c
> +void knot_cloud_set_log_priority(char * priority)
```suggestion
void knot_cloud_set_log_priority(char *priority)
```

2020-08-17 17:19 UTC, alla3 commented on src/knot_cloud.h
> +void knot_cloud_set_log_priority(char * priority);
```suggestion
void knot_cloud_set_log_priority(char *priority);
```

2020-08-17 17:19 UTC, alla3 commented on src/log.c
> +void log_set_priority(int priority)
Please, add a blank line between functions.

2020-08-19 01:37 UTC, vitbaq requested changes
Almost there, the last things to change.

2020-08-19 01:37 UTC, vitbaq commented on src/log.c
> +void log_set_priority(int priority)
Change the order of the functions. Put this function after the log_ell_enable

2020-08-19 01:37 UTC, vitbaq commented on src/log.c
> +void log_ell_enable()
Change to `void log_ell_enable(void)`

2020-08-19 01:37 UTC, vitbaq commented on src/log.h
> +void log_ell_enable();
Change to `void log_ell_enable(void)`

2020-08-19 01:42 UTC, vitbaq commented on src/log.c
> +void log_ell_enable()
Reason for this: [link](https://softwareengineering.stackexchange.com/questions/286490/what-is-the-difference-between-function-and-functionvoid/287002)

2020-08-19 13:34 UTC, vitbaq approved these changes

2020-08-20 22:38 UTC, alla3 approved these changes

2020-08-21 14:11 UTC, merged