Separate AMQP timeouts
CESARBR/knot-cloud-sdk-c pull request #8
Opened 2020-08-24 21:28 UTC by kbcvcbk

Separate AMQP "consume timeout" from "attempt connection timeout" so the latter conforms to (RabbitMQ Handshake Timeout specification) [https://www.rabbitmq.com/networking.html#handshake-timeout].

2020-08-25 14:42 UTC, CaioCordeiro requested changes
LGTM. I've requested some small code formatting changes, but the code looks good.

2020-08-25 14:42 UTC, CaioCordeiro commented on src/mq.c
> +	struct timeval timeout = {.tv_sec = MQ_CONNECTION_CONNECT_TIMEOUT_SEC};
Is removing those blank spaces necessary?

2020-08-25 14:42 UTC, CaioCordeiro commented on src/mq.c
> +	struct timeval time_out = {.tv_usec = MQ_CONNECTION_CONSUME_TIMEOUT_US};
Is removing those blank spaces necessary?

2020-08-28 12:51 UTC, vitbaq approved these changes

2020-09-02 15:11 UTC, CaioCordeiro approved these changes

2020-09-02 17:01 UTC, agms-cesar approved these changes

2020-09-04 04:24 UTC, merged